export default defineAppConfig({
  ui: {
    colors: {
      primary: 'primary',
      secondary: 'secondary',
      success: 'green',
      info: 'blue',
      warning: 'yellow',
      error: 'red',
      neutral: 'neutral'
    },

    icons: {
      arrowDown: 'i-tabler-arrow-down',
      arrowLeft: 'i-tabler-arrow-left',
      arrowRight: 'i-tabler-arrow-right',
      arrowUp: 'i-tabler-arrow-up',
      caution: 'i-tabler-alert-circle',
      check: 'i-tabler-check',
      chevronDoubleLeft: 'i-tabler-chevrons-left',
      chevronDoubleRight: 'i-tabler-chevrons-right',
      chevronDown: 'i-tabler-chevron-down',
      chevronLeft: 'i-tabler-chevron-left',
      chevronRight: 'i-tabler-chevron-right',
      chevronUp: 'i-tabler-chevron-up',
      close: 'i-tabler-x',
      copy: 'i-tabler-copy',
      copyCheck: 'i-tabler-copy-check',
      dark: 'i-tabler-moon',
      drag: 'i-tabler-grip-vertical',
      ellipsis: 'i-tabler-dots',
      error: 'i-tabler-circle-x',
      external: 'i-tabler-external-link',
      eye: 'i-tabler-eye',
      eyeOff: 'i-tabler-eye-off',
      file: 'i-tabler-file',
      folder: 'i-tabler-folder',
      folderOpen: 'i-tabler-folder-open',
      hash: 'i-tabler-hash',
      info: 'i-tabler-info-circle',
      light: 'i-tabler-sun',
      loading: 'i-tabler-loader',
      menu: 'i-tabler-menu-2',
      minus: 'i-tabler-minus',
      panelClose: 'i-tabler-panel-left-close',
      panelOpen: 'i-tabler-panel-left-open',
      plus: 'i-tabler-plus',
      reload: 'i-tabler-refresh',
      search: 'i-tabler-search',
      stop: 'i-tabler-square',
      success: 'i-tabler-circle-check',
      system: 'i-tabler-device-desktop',
      tip: 'i-tabler-lightbulb',
      upload: 'i-tabler-upload',
      warning: 'i-tabler-alert-triangle'
    }
  }
})
